### ISSUE TITLE
Kdenlive 22.08.1 using "mov" files as proxy

### ISSUE THREAD

**Issue by daudtivan** [booleanexception/lrvkdenlive#2]
I was a happy user of lrvkdenlive until I had my notebook upgraded to elementaryOS 6.1 and had Kdenlive on 22.08.1.
I noticed proxy clips were being generate, no matter if I had them "parsed" by lrvkdenlive or not.
Checked my proxy cache and found 2 files with same name: one ".mkv" and another ".mov".
Question is: should lrvkdenlive be updated to reflect most recent version of kdenlive, or it's something I can modify on Kdenlive settings?

And thanks for the good work. Helped me save a lot of time so far.

**Comment by booleanexception** [comment]
Hi,

yes, filenames changed to .mov. However Kdenlive now can import those LRVs itself in the newer versions, they seem to have implemented this idea by themselves (I didn't test it myself as I dont use GoPros anymore).

Greetings!

**Comment by antonna987** [comment]
> Hi,
> 
> yes, filenames changed to .mov. However Kdenlive now can import those LRVs itself in the newer versions, they seem to have implemented this idea by themselves (I didn't test it myself as I dont use GoPros anymore).
> 
> Greetings!

Kdenlive LRVs import doesn't work (at least for me with ubuntu and kdenlive-24.05.2-x86_64.AppImage), so personally I found this tool with simple fix to .mov very handy
